services:

    backend:
        build:
          context: ./backend

        container_name: lucidsight-backend
        ports:
          - "5000:5000"

        environment:
          EMAILUSER: ${EMAILUSER}
          EMAILPWD: ${EMAILPWD}

        restart: unless-stopped



    frontend:

        image: lucidsight-frontend:${BUILD_NUMBER:latest}

        build:
          context: .

        container_name: lucidsight-frontend
        ports:
          - "8000:80"

        depends_on:
          - backend

        restart: unless-stopped

