services:

  backend:
    image: 065194293194.dkr.ecr.us-east-1.amazonaws.com/lucidsight-backend:latest

    container_name: lucidsight-backend

    ports:
      - "5000:5000"

    environment:
      EMAILUSER: ${EMAILUSER}
      EMAILPWD: ${EMAILPWD}

    networks:
      default:
        aliases:
          - backend-service

    restart: unless-stopped


  frontend:
    image: 065194293194.dkr.ecr.us-east-1.amazonaws.com/lucidsight-frontend:latest

    container_name: lucidsight-frontend

    ports:
      - "8000:80"

    depends_on:
      - backend

    restart: unless-stopped